IP_FASTQ_FILES: #(comment: Do not use underscores in TF names (here MAX))
IP_FASTA_FILES:
IP_BED_FILES:
IP_SHIFTEDBED_FILES:

BG_FASTQ_FILES: #(comment: .fastq extension)
BG_FASTA_FILES: #(comment: .fa extension)
BG_BED_FILES: #(comment: .bedweight or .bed extension)
BG_SHIFTEDBED_FILES: #(comment: .bedweight or .bed extension)

OUT_DIR: OUTPUT
ADAPTOR:
ANNOTATION_TYPE: dm3-none-aln2.3
GENOME: dm3
GENDIR_PATH: /import/bc2/data/databases/UCSC/dm3
CHROMOSOME_INFO: /import/bc2/home/nimwegen/GROUP/hseq_pipeline/general/chromInfo/dm3chrs.tab
REPEAT_PATH:     /import/bc2/home/nimwegen/GROUP/hseq_pipeline/general/repeatMask/dm3
ANNOTATION_FILE: /import/bc2/home/nimwegen/GROUP/4severin/Drosophila_melanogaster.BDGP5.66.genes.bed
WMLIBRARY: /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/WMs/WMs_drosophila
FDR: 0.1
WINDOW: 500
BACKGROUND_WINDOW: 2000
STEP: 250
DO_MOTIF_FINDING: TRUE
USER:
PROJECTLEADER: project_nimwegen
RENAME_TAG:
IP_FASTQ_DESCRIPTION:
BG_FASTQ_DESCRIPTION:
IP_FASTA_DESCRIPTION:
BG_FASTA_DESCRIPTION:


##invariant, do not touch:
FMI_PATH:
    /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/fmitools
ANDURIL_COMPONENTS_PATH:
    /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/components
ANDURIL_TEMPLATES_PATH:
    /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/templates
ANDURIL_HOME:
    /import/bc2/soft/app/anduril/1.2.5/Linux
PERL_PATH:
    /import/bc2/soft/app/perl/5.10.1/Linux/bin/perl
PYTHON_PATH:
    /import/bc2/home/nimwegen/GROUP/local/bin/python
R_PATH:
    /import/bc2/soft/Linux/bin/R
R_LIBS_USER:
    /import/bc2/home/nimwegen/GROUP/local/lib/R
SORT_TMPDIR:
    /import/bc2/scratch/tmp/
USE_CLUSTER:
    TRUE
QUEUE_NAMES:
    long=fs_long
    verylong=fs_very_long
    long_hm=fs_long@@x3755
    verylong_hm=fs_very_long_hm
    sjpn_long_hm=fs_long@@x3755
    multi_long_hm=fs_long@@x3755
THREAD_NUMBER: 8
ALIGN_PIPE_PATH:
    /import/bc2/home/nimwegen/GROUP/AlignmentPipeline/scripts/pipeline.pl
BEDTOOLS_PATH:
    /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/fmitools/soft/bedtools
PHYLOGIBBS_PATH:
    /import/bc2/home/nimwegen/GROUP/software/phylogibbs-1.2/src/phylogibbs
MYLOGO_PATH:
    /import/bc2/home/nimwegen/GROUP/Scripts/weblogo/mylogo
WEBLOGO_PATH:
    /import/bc2/home/nimwegen/GROUP/software/weblogo-3.4/weblogo
MOTEVO_PATH:
    /import/bc2/home/nimwegen/GROUP/software/motevo_ver1.03/bin/motevo
MOTEVOUFE_PATH:
    /import/bc2/home/nimwegen/GROUP/software/motevo_ver1.03/bin/runUFE
DRMAA_LIBRARY_PATH:
    /import/bc2/soft/app/SGE/6.1/Linux/lib/lx24-amd64/libdrmaa.so
WEBLOGO_PATH:
    /import/bc2/home/nimwegen/bergerse00/Projects/ChIPseq-pipeline/scripts/weblogo-3.4/weblogo
